### PR TITLE
Added Basic Binary Tree stucture based problems

### PR DESCRIPTION
**Pull request by bplm**
Added Structure based Traversal problems and solutions on Binary Tree.

### CODE REVIEW

**Comment by Vishruth-S** [comment]
Thanks for your contributions.
Do star ⭐ this repo.
Also note that this repo is no longer accepting PRs.

**Review by Vishruth-S — APPROVED** [review]

**Comment by bplm** [comment]
> Thanks for your contributions.
> Do star ⭐ this repo.
> Also note that this repo is no longer accepting PRs.

@Vishruth-S  I had done 3 PRs previously , will they be counted as accepted for the Hacktoberfest2020?
Since , only one is labelled as hacktoberfest-accepted till now. Kindly let me know!!

 The Competitive Code is accepting PRs?

**Comment by Vishruth-S** [comment]
@bplm If the PR was approved and merged in a repo having the `hacktoberfest` topic, then the `hacktoberfest-accepted` label is not needed, it will anyway be accepted.
Check this link for more info: https://hacktoberfest.digitalocean.com/hacktoberfest-update

And yes, the CompetitiveCode repo is accepting PRs provided it follows all guidelines mentioned there.

**Comment by bplm** [comment]
image


@Vishruth-S  When I commit and push , after that when I CLICK ON CREATE NEW PULL REQUEST, this page opens up ; How can I create pull requests?Can you please help with the issue?

**Pull request merged**
